name: Tag Release
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # js-client-npm-release:
  #   name: Publish JS client
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: get-version
  #       run: |
  #         version=$(echo "${{github.ref}}" | sed 's/^refs\/tags\/v//')
  #         echo "::set-output name=version::$version"
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'
  #         registry-url: 'https://registry.npmjs.org'
  #         scope: '@dsps'
  #     - name: Yarn publish
  #       run: |
  #         yarn install --frozen-lockfile
  #         yarn publish --frozen-lockfile --non-interactive --new-version ${{ steps.get-version.outputs.version }} --no-git-tag-version
  #       working-directory: client/js
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
